/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: c81b4c2c6462a6bcab31a3bb27d4f59a)
interface __BaseEnv_Env {
	CIPHERTEXT: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
	APP_ORIGIN: string;
	UPLOADS_ENABLED: string;
	GLOBAL_BYTE_CAP: string;
	IP_CREATE_LIMIT: string;
	GLOBAL_CREATE_LIMIT: string;
	RATE_LIMIT_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ORIGIN" | "UPLOADS_ENABLED" | "GLOBAL_BYTE_CAP" | "IP_CREATE_LIMIT" | "GLOBAL_CREATE_LIMIT" | "RATE_LIMIT_SECRET">> {}
}
